const SET_DISH = "SET_DISH";
const SET_DRINKS = "SET_DRINKS";
const CLEAR_ORDER = "CLEAR_ORDER";
const SET_ALL_ORDERS = "SET_ALL_ORDERS";

export { SET_DISH, SET_ALL_ORDERS, SET_DRINKS, CLEAR_ORDER };
